name: Webhook Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -X GET \
               --url "http://${{ secrets.COOLIFY_IP }}:8000/api/v1/deploy?uuid=${{ secrets.COOLIFY_UUID }}&force=false" \
               -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}"